version: "3.7"

services:
    client:
        build: client
        ports: 
        - 3000:3000
        depends_on:
        - server
    server:
        build: server
        ports: 
        - 8000:8000