version: "3.7"

services:
    client:
        build:
            context: client
            dockerfile: Dockerfile
        ports: 
        - 3000:3000
        depends_on:
        - server
        volumes:
        - './client:/usr/src/app'
        - '/usr/src/app/node_modules'
        - '/usr/src/app/.next'
    server:
        build: server
        ports: 
        - 8000:8000